language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install matplotlib primer3-py
  - pip install coveralls pytest-cov==2.6 pytest==3.2.3
  - sudo apt-get install ncbi-blast+
  - pip install -e .[reports]
# command to run tests
script:
  - python -m pytest -v --cov dnachisel --cov-report term-missing

after_success:
  - coveralls
